// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgYREh0PlUo7QsIz99IwkiuRZL5ZCEwb4',
    appId: '1:30659033307:web:9b28f5c9d337d0be4ab4fe',
    messagingSenderId: '30659033307',
    projectId: 'awesome-f2d84',
    authDomain: 'awesome-f2d84.firebaseapp.com',
    storageBucket: 'awesome-f2d84.firebasestorage.app',
    measurementId: 'G-LP8MEB7KJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwE9aJ16heMtmh8bUwK-FGvGjHgxWjrto',
    appId: '1:30659033307:android:cefaca2f7121d1d74ab4fe',
    messagingSenderId: '30659033307',
    projectId: 'awesome-f2d84',
    storageBucket: 'awesome-f2d84.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTELz4ympURLIhts5_E5Rub0VQaFMYy9s',
    appId: '1:30659033307:ios:413f04fe4228679b4ab4fe',
    messagingSenderId: '30659033307',
    projectId: 'awesome-f2d84',
    storageBucket: 'awesome-f2d84.firebasestorage.app',
    iosBundleId: 'com.example.payrollSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTELz4ympURLIhts5_E5Rub0VQaFMYy9s',
    appId: '1:30659033307:ios:413f04fe4228679b4ab4fe',
    messagingSenderId: '30659033307',
    projectId: 'awesome-f2d84',
    storageBucket: 'awesome-f2d84.firebasestorage.app',
    iosBundleId: 'com.example.payrollSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgYREh0PlUo7QsIz99IwkiuRZL5ZCEwb4',
    appId: '1:30659033307:web:14fb8058a11443314ab4fe',
    messagingSenderId: '30659033307',
    projectId: 'awesome-f2d84',
    authDomain: 'awesome-f2d84.firebaseapp.com',
    storageBucket: 'awesome-f2d84.firebasestorage.app',
    measurementId: 'G-1R8JPN5RYW',
  );
}
